### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by SMOLKEYS** [Redstonneur1256/Mindustry-ModLib#1]
it is exactly what it says

if possible

**Comment by Redstonneur1256** [comment]
I am already working on it, Android support should be added in the next version

**Comment by SMOLKEYS** [comment]
Sweet, now i can give mixins a try

**Comment by zzcuongngaozz** [comment]
> I am already working on it, Android support should be added in the next version

Can u make it support android 🫂
