### ISSUE TITLE
mod.json

### ISSUE THREAD

**Issue by bDennisdbRichterd** [Redstonneur1256/Mindustry-ModLib#3]
Were is mod.json can't use mod cuz no mod.json

**Comment by Redstonneur1256** [comment]
The mod.json is located in the assets folder, could you provide more details about why the mod.json is missing ? It's automatically included in the jars available on the releases page.

**Comment by bDennisdbRichterd** [comment]
Mindustry doesn't register that u need to put it at the root of the .zip like every other mod

**Comment by Redstonneur1256** [comment]
No you do not need to put it in the root directory as long as the folder it's in is included into the jar/zip which is the case here https://github.com/Redstonneur1256/Mindustry-ModLib/blob/7cdce7011da2fe630458453c2ef5420714b25858/Mod/build.gradle#L15

**Comment by bDennisdbRichterd** [comment]
For me it showed an error

**Comment by Redstonneur1256** [comment]
How did you import the mod
