### ISSUE TITLE
Crash in he newest steam build with the newest release of this mod

### ISSUE THREAD

**Issue by 1ue999** [Redstonneur1256/Mindustry-ModLib#4]
the log is below
[crash-report-10_28_2023_23_47_17.txt](https://github.com/Redstonneur1256/Mindustry-ModLib/files/13196772/crash-report-10_28_2023_23_47_17.txt)

**Comment by Redstonneur1256** [comment]
I do not have the game on steam thus making it impossible for me to test the mod on the steam version, I'll try to fix it when I can. You should be able to use the mod with the standalone version of the game and it should work fine as a workaround for now.
